spring.application.name=simple-ecommerce-store
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_store
spring.datasource.username=root
spring.datasource.password=Roshan@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf (optional, just disables caching during development)
spring.thymeleaf.cache=false

# Server port (optional, default is 8080)
server.port=8080
# JWT
jwt.secret=ecommerce_secret_key_1234567890_abcdefgh
jwt.expiration=86400000